# Generated by Django 5.1.6 on 2025-04-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cargo_description_cargo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoreview',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (5, '5'), (3, '3'), (0, '0')], default=0),
        ),
    ]
