# Generated by Django 5.1.6 on 2025-04-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cargoreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoreview',
            name='stars',
            field=models.IntegerField(choices=[(2, '2'), (0, '0'), (5, '5'), (3, '3'), (1, '1'), (4, '4')], default=0),
        ),
    ]
