# Generated by Django 5.1.6 on 2025-04-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cargoreview_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('ad_type', models.CharField(choices=[('Banner', 'Banner'), ('Video', 'Video'), ('Text', 'Text')], default='Banner', max_length=20)),
                ('duration_days', models.IntegerField(choices=[(1, '1 kun'), (3, '3 kun'), (7, '1 hafta'), (14, '2 hafta'), (30, '1 oy')], default=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Korib chiqilmoqda', 'Korib chiqilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Korib chiqilmoqda', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='advertisements/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ("O'qilgan", "O'qilgan"), ('Javob berilgan', 'Javob berilgan')], default='Yangi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cargoreview',
            name='stars',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (1, '1'), (0, '0'), (4, '4'), (5, '5')], default=0),
        ),
    ]
